# Generated by Django 4.1.13 on 2024-04-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_remove_order_paymentid_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
