# Generated by Django 4.1.13 on 2024-04-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_user_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_information',
            name='available_icu_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='emergency_cabin_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='general_bed_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='regular_cabin_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='vip_cabin_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
