# Generated by Django 4.1.13 on 2024-04-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0045_alter_doctor_information_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_information',
            name='consultation_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
