# Generated by Django 4.1.13 on 2024-04-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0046_alter_doctor_information_consultation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_information',
            name='dob',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='nid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='report_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='visiting_hour',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
