# Generated by Django 4.1.13 on 2024-04-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0047_alter_doctor_information_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
